services:
  app_and_code:
    build: .
    image: credit_risk_project
# note that in production with multiple containers, would probably use default name instead
    container_name: credit_risk_container
    ports: 
      - "8000:8000"
    volumes: 
      - ./models:/app/models/
      - ./logs:/app/logs/