train_size: 0.7
validation_size: 0.1
test_size: 0.2
random_seed: 42
training_loss: 'mean_squared_error'
num_clients_train: 100
random_seed: 42

Lasso_params:
  alpha: 0.1

XGBoost_params:
  # obtained via optuna hyperparameter tuning
  learning_rate: 0.12538526747297057
  max_depth: 10
  min_child_weight: 1
  subsample: 0.7449815181068469
  colsample_bytree: 0.8429379706997666
  lambda: 0.40705331934950384
  n_estimators: 200
  early_stop_rounds: 10

LSTM_params:
  seq_length: 168
  batch_size: 32
  train_stride_low: 13
  train_stride_high: 23
  validate_stride: 12
  test_stride: 1
  hidden_size: 10
  learning_rate: 1.0e-4
  weight_decay: 1.0e-3
  epochs: 50
  patience: 5
  delta: 1.0e-3

optuna_params:
  n_trials: 20
  timeout: 600
