# .github/worklows/run_tests.yml

on:

    push:
        branches: ['master']
        paths:
          - 'credit_risk_project/**'

jobs: 

# first run the unit tests - without setting up API
  UnitTests:

# test multiple os
    runs-on: ${{ matrix.os }}

# set default directory to project directory for now
    defaults:
      run:
        working-directory: credit_risk_project
# define matrix (array of python versions to perform test action on) 
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", '3.14']
        os: [ubuntu-latest, windows-latest]
    steps:
# first clone the repo into the runner's VM
    - uses: actions/checkout@v5
# then set up python, using matrix of versions defined above
    - name: Setting up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
# then install packages of repo, using pip and requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
# now run test file using pytest
    - name: Run tests using pytest
      run: pytest tests/test_all.py -m unit

# test that works when set up docker
  IntegrationTests:

  # test on linux only for now
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: credit_risk_project
      steps:
  # first clone the repo into the runner's VM
      - uses: actions/checkout@v5

  # set up the container
      - name: Start container
        run: docker compose up -d
  # check logs of container to see if uvicorn started
      - name: check container logs
        run: docker logs credit_risk_container
  # loop to wait for server to be ready
      - name: wait for server to be ready
        run: |
          for i in {1..10}; do
             curl http://127.0.0.1:8000/health && break
             echo 'check for containers'
             docker ps -a
             sleep 30
          done
  # now run test file using pytest
      - name: Run tests using pytest
        run: pytest tests/test_all.py -m integration
  # tear down container afterwards
      - name: tear down container
        run: docker compose down   


